version: '3'
services:
  beast-server:
    build:
      context: .
      dockerfile: beast.Dockerfile
    ports:
      - 1000:3000
    env_file: .env.docker
    volumes:
      - ./volumes:/volumes
      - /mnt/libraries:/mnt/libraries
